x=10
y=5
sum=x+y
difference=x-y
product=x*y
division_floor=x//y
division=x/y
remainder=x%y
exponential=x**y
print("x=",x)
print("y=",y)
print("sum=",sum)
print("difference=",difference)
print("product=",product)
print("floor division=",division_floor)
print("division=",division)
print("remainder=",remainder)
print("exponential=",exponential)